name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install system deps
        run: sudo apt-get update && sudo apt-get install -y libgl1
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install pytest pytest-cov hypothesis
      - name: Run tests
        run: pytest -q
      - name: Coverage summary
        if: always()
        run: |
          python - <<'EOF'
          import json, sys
          # Simple placeholder; detailed coverage already printed by pytest-cov
          print('Tests completed.')
          EOF

